export const profileFormMessages = {
  en: { personal: "Personal information", personalHelp: "Keep your public identity up to date.", name: "Display name", email: "Email", emailHelp: "Managed by your authentication provider.", career: "Study goal", careerPlaceholder: "Example: Public service exam", bio: "About you", bioPlaceholder: "Tell us about your study journey", contact: "Contact and social profiles", phone: "Phone (optional)", instagram: "Instagram", tiktok: "TikTok", privacy: "Privacy and visibility", privacyHelp: "Choose what other students can see.", private: "Private", privateHelp: "Your profile is not visible.", basic: "Basic public", basicHelp: "Only name and photo are visible.", public: "Complete public", publicHelp: "Name, photo, bio and social profiles are visible.", save: "Save changes", saving: "Saving...", saved: "Profile saved.", invalid: "Review the entered information.", loadError: "Could not load your profile.", saveError: "Could not save your profile." },
  "pt-BR": { personal: "Informações pessoais", personalHelp: "Mantenha sua identidade pública atualizada.", name: "Nome de exibição", email: "E-mail", emailHelp: "Gerenciado pelo seu provedor de autenticação.", career: "Objetivo de estudo", careerPlaceholder: "Exemplo: concurso público", bio: "Sobre você", bioPlaceholder: "Conte um pouco sobre sua jornada de estudos", contact: "Contato e redes sociais", phone: "Telefone (opcional)", instagram: "Instagram", tiktok: "TikTok", privacy: "Privacidade e visibilidade", privacyHelp: "Escolha o que outros estudantes podem visualizar.", private: "Privado", privateHelp: "Seu perfil não fica visível.", basic: "Básico público", basicHelp: "Somente nome e foto ficam visíveis.", public: "Completo público", publicHelp: "Nome, foto, biografia e redes sociais ficam visíveis.", save: "Salvar alterações", saving: "Salvando...", saved: "Perfil salvo.", invalid: "Revise as informações preenchidas.", loadError: "Não foi possível carregar seu perfil.", saveError: "Não foi possível salvar seu perfil." },
  "pt-PT": { personal: "Informações pessoais", personalHelp: "Mantenha a sua identidade pública atualizada.", name: "Nome de apresentação", email: "E-mail", emailHelp: "Gerido pelo seu fornecedor de autenticação.", career: "Objetivo de estudo", careerPlaceholder: "Exemplo: concurso público", bio: "Sobre si", bioPlaceholder: "Conte um pouco sobre o seu percurso de estudo", contact: "Contacto e redes sociais", phone: "Telefone (opcional)", instagram: "Instagram", tiktok: "TikTok", privacy: "Privacidade e visibilidade", privacyHelp: "Escolha o que outros estudantes podem ver.", private: "Privado", privateHelp: "O seu perfil não fica visível.", basic: "Básico público", basicHelp: "Apenas o nome e a foto ficam visíveis.", public: "Completo público", publicHelp: "Nome, foto, biografia e redes sociais ficam visíveis.", save: "Guardar alterações", saving: "A guardar...", saved: "Perfil guardado.", invalid: "Reveja as informações preenchidas.", loadError: "Não foi possível carregar o perfil.", saveError: "Não foi possível guardar o perfil." },
  es: { personal: "Información personal", personalHelp: "Mantén actualizada tu identidad pública.", name: "Nombre visible", email: "Correo", emailHelp: "Gestionado por tu proveedor de autenticación.", career: "Objetivo de estudio", careerPlaceholder: "Ejemplo: oposición pública", bio: "Sobre ti", bioPlaceholder: "Cuenta tu recorrido de estudio", contact: "Contacto y redes sociales", phone: "Teléfono (opcional)", instagram: "Instagram", tiktok: "TikTok", privacy: "Privacidad y visibilidad", privacyHelp: "Elige qué pueden ver otros estudiantes.", private: "Privado", privateHelp: "Tu perfil no es visible.", basic: "Básico público", basicHelp: "Solo el nombre y la foto son visibles.", public: "Completo público", publicHelp: "Nombre, foto, biografía y redes sociales son visibles.", save: "Guardar cambios", saving: "Guardando...", saved: "Perfil guardado.", invalid: "Revisa la información ingresada.", loadError: "No se pudo cargar tu perfil.", saveError: "No se pudo guardar tu perfil." },
  fr: { personal: "Informations personnelles", personalHelp: "Gardez votre identité publique à jour.", name: "Nom affiché", email: "E-mail", emailHelp: "Géré par votre fournisseur d’authentification.", career: "Objectif d’étude", careerPlaceholder: "Exemple : concours public", bio: "À propos", bioPlaceholder: "Présentez votre parcours d’étude", contact: "Contact et réseaux sociaux", phone: "Téléphone (facultatif)", instagram: "Instagram", tiktok: "TikTok", privacy: "Confidentialité et visibilité", privacyHelp: "Choisissez ce que les autres étudiants peuvent voir.", private: "Privé", privateHelp: "Votre profil n’est pas visible.", basic: "Public basique", basicHelp: "Seuls le nom et la photo sont visibles.", public: "Public complet", publicHelp: "Nom, photo, biographie et réseaux sociaux sont visibles.", save: "Enregistrer", saving: "Enregistrement...", saved: "Profil enregistré.", invalid: "Vérifiez les informations saisies.", loadError: "Impossible de charger votre profil.", saveError: "Impossible d’enregistrer votre profil." },
} as const

export const profileLoadingMessages = {
  en: "Loading profile...",
  "pt-BR": "Carregando perfil...",
  "pt-PT": "A carregar perfil...",
  es: "Cargando perfil...",
  fr: "Chargement du profil...",
} as const
