"use client"

import { useRef } from "react"
import { ChevronLeft, ChevronRight, Landmark } from "lucide-react"
import type { QuestionFilterOption } from "@/lib/questions/filter/types"

export function QuestionContextCarousel({ options, value, onChange }: { options: QuestionFilterOption[]; value: string; onChange: (value: string) => void }) {
  const scrollRef = useRef<HTMLDivElement>(null)
  const items = [{ value: "", label: "Todas" }, ...options]
  const scroll = (direction: "left" | "right") => scrollRef.current?.scrollBy({ left: direction === "left" ? -240 : 240, behavior: "smooth" })
  return <div className="relative space-y-4 group/carousel"><h3 className="ml-1 text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground/30">Instituições</h3><div className="relative"><button type="button" aria-label="Anterior" onClick={() => scroll("left")} className="absolute -left-2 top-1/2 z-10 flex size-10 -translate-y-1/2 items-center justify-center rounded-full border border-border/40 bg-background/80 text-muted-foreground opacity-0 shadow-xl backdrop-blur-md transition-all hover:scale-110 hover:text-primary group-hover/carousel:opacity-100"><ChevronLeft className="size-5" /></button><div ref={scrollRef} className="no-scrollbar flex gap-4 overflow-x-auto scroll-smooth pb-1">{items.map((item) => { const active = item.value === value; return <button key={item.value || "all"} type="button" onClick={() => onChange(item.value)} className={`flex h-36 min-w-[120px] shrink-0 flex-col items-center justify-center rounded-3xl border transition-all hover:scale-[1.02] active:scale-[0.98] ${active ? "border-primary bg-background shadow-lg ring-1 ring-primary/20" : "border-border/40 bg-muted/5 hover:border-primary/20 hover:bg-muted/10"}`}><div className={`mb-2 flex size-14 items-center justify-center rounded-2xl border transition-all ${active ? "scale-110 border-primary/20 bg-primary/5" : "border-border/10 bg-muted/5"}`}><Landmark className={`size-6 ${active ? "text-primary" : "text-muted-foreground/30"}`} /></div><span className={`max-w-[100px] truncate text-sm font-black tracking-tight ${active ? "text-foreground" : "text-muted-foreground/80"}`}>{item.label}</span><span className="mt-2 w-full border-t border-border/10 pt-2 text-center text-[8px] font-bold uppercase tracking-[0.15em] text-muted-foreground/30">Instituição</span></button> })}</div><button type="button" aria-label="Próximo" onClick={() => scroll("right")} className="absolute -right-2 top-1/2 z-10 flex size-10 -translate-y-1/2 items-center justify-center rounded-full border border-border/40 bg-background/80 text-muted-foreground opacity-0 shadow-xl backdrop-blur-md transition-all hover:scale-110 hover:text-primary group-hover/carousel:opacity-100"><ChevronRight className="size-5" /></button></div></div>
}
