import type { Locale } from "@/lib/i18n/messages"

export const rankingMessages: Record<Locale, {
  title: string; subtitle: string; period: string; scope: string; weekly: string; monthly: string; allTime: string;
  global: string; career: string; discipline: string; yourPosition: string; points: string; answered: string; correct: string;
  accuracy: string; position: string; streak: string; evolution: string; emptyTitle: string; emptyDescription: string; comingSoon: string
}> = {
  en: { title: "Rankings", subtitle: "Track your progress and compare your performance.", period: "Period", scope: "Ranking", weekly: "This week", monthly: "This month", allTime: "All time", global: "Global", career: "Career", discipline: "Discipline", yourPosition: "Your position", points: "points", answered: "answered", correct: "correct", accuracy: "accuracy", position: "Position", streak: "Study streak", evolution: "Evolution", emptyTitle: "Ranking data is not available yet", emptyDescription: "Once you answer questions, your performance will appear here.", comingSoon: "Coming soon" },
  "pt-BR": { title: "Rankings", subtitle: "Acompanhe seu progresso e compare seu desempenho.", period: "Período", scope: "Ranking", weekly: "Esta semana", monthly: "Este mês", allTime: "Todo o período", global: "Geral", career: "Carreira", discipline: "Disciplina", yourPosition: "Sua posição", points: "pontos", answered: "respondidas", correct: "acertos", accuracy: "aproveitamento", position: "Posição", streak: "Sequência", evolution: "Evolução", emptyTitle: "Ainda não há dados no ranking", emptyDescription: "Quando você responder questões, seu desempenho aparecerá aqui.", comingSoon: "Em breve" },
  "pt-PT": { title: "Rankings", subtitle: "Acompanhe o seu progresso e compare o seu desempenho.", period: "Período", scope: "Ranking", weekly: "Esta semana", monthly: "Este mês", allTime: "Todo o período", global: "Geral", career: "Carreira", discipline: "Disciplina", yourPosition: "A sua posição", points: "pontos", answered: "respondidas", correct: "acertos", accuracy: "aproveitamento", position: "Posição", streak: "Sequência", evolution: "Evolução", emptyTitle: "Ainda não existem dados no ranking", emptyDescription: "Quando responder a questões, o seu desempenho aparecerá aqui.", comingSoon: "Em breve" },
  es: { title: "Clasificaciones", subtitle: "Sigue tu progreso y compara tu rendimiento.", period: "Período", scope: "Clasificación", weekly: "Esta semana", monthly: "Este mes", allTime: "Todo el período", global: "General", career: "Carrera", discipline: "Materia", yourPosition: "Tu posición", points: "puntos", answered: "respondidas", correct: "aciertos", accuracy: "rendimiento", position: "Posición", streak: "Racha", evolution: "Evolución", emptyTitle: "Aún no hay datos de clasificación", emptyDescription: "Cuando respondas preguntas, tu rendimiento aparecerá aquí.", comingSoon: "Próximamente" },
  fr: { title: "Classements", subtitle: "Suivez votre progression et comparez vos performances.", period: "Période", scope: "Classement", weekly: "Cette semaine", monthly: "Ce mois-ci", allTime: "Tout le temps", global: "Global", career: "Carrière", discipline: "Matière", yourPosition: "Votre position", points: "points", answered: "répondues", correct: "bonnes réponses", accuracy: "réussite", position: "Position", streak: "Série", evolution: "Évolution", emptyTitle: "Les données du classement ne sont pas encore disponibles", emptyDescription: "Après vos premières réponses, vos performances apparaîtront ici.", comingSoon: "Bientôt" },
}
