import type { SimuladoItem } from "./types"

export const INITIAL_SIMULADOS: SimuladoItem[] = [
  {
    id: "sim-1",
    title: "Português",
    subject: "Língua Portuguesa",
    questionsCount: 50,
    duration: "1h",
    difficulty: "Médio",
    description: "Teste seus conhecimentos e veja como está sua preparação em Língua Portuguesa.",
    quote: "Disciplina é o que te aproxima do seu objetivo.",
  },
  {
    id: "sim-2",
    title: "Direito Constitucional",
    subject: "Direito Constitucional",
    questionsCount: 40,
    duration: "1h",
    difficulty: "Difícil",
    description: "Avalie seu domínio sobre princípios fundamentais, direitos e garantias individuais.",
    quote: "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  },
  {
    id: "sim-3",
    title: "Direito Administrativo",
    subject: "Direito Administrativo",
    questionsCount: 45,
    duration: "1h",
    difficulty: "Médio",
    description: "Pratique com questões sobre atos administrativos, licitações, contratos e servidores.",
    quote: "A constância é a ponte que une o estudo à aprovação.",
  },
  {
    id: "sim-4",
    title: "Raciocínio Lógico",
    subject: "Raciocínio Lógico-Matemático",
    questionsCount: 30,
    duration: "45m",
    difficulty: "Difícil",
    description: "Exercite proposições, diagramas lógicos, equivalências e análise combinatória.",
    quote: "Foco no processo, a mente afiada resolve qualquer desafio.",
  },
  {
    id: "sim-5",
    title: "Direito Penal",
    subject: "Direito Penal & Processo Penal",
    questionsCount: 40,
    duration: "1h",
    difficulty: "Médio",
    description: "Simulado com foco em teoria do crime, tipicidade, culpabilidade e penas.",
    quote: "A dedicação de hoje constrói a estabilidade do amanhã.",
  },
  {
    id: "sim-6",
    title: "Informática",
    subject: "Noções de Informática",
    questionsCount: 30,
    duration: "40m",
    difficulty: "Fácil",
    description: "Questões sobre segurança da informação, redes de computadores e sistemas operacionais.",
    quote: "Cada questão resolvida é um passo a mais rumo ao topo.",
  },
]
