import type { Locale } from "@/lib/i18n/messages"

export const questionFilterMessages: Record<Locale, {
  title: string; active: string; show: string; hide: string; search: string; searchPlaceholder: string;
  all: string; clear: string; selected: string; empty: string; discipline: string; subject: string;
  topic: string; difficulty: string; year: string; board: string; institution: string; career: string;
  education: string; alternatives: string; resultEmpty: string
}> = {
  en: { title: "Filter questions", active: "active", show: "Show filters", hide: "Hide filters", search: "Search", searchPlaceholder: "Code, subject or question statement", all: "All", clear: "Clear filters", selected: "selected filter(s)", empty: "No filters selected", discipline: "Subject", subject: "Topic", topic: "Subtopic", difficulty: "Difficulty", year: "Year", board: "Exam board", institution: "Institution", career: "Career", education: "Education level", alternatives: "Alternatives", resultEmpty: "No questions found." },
  "pt-BR": { title: "Filtrar questões", active: "ativos", show: "Mostrar filtros", hide: "Ocultar filtros", search: "Buscar", searchPlaceholder: "Código, disciplina ou enunciado", all: "Todas", clear: "Limpar filtros", selected: "filtro(s) selecionado(s)", empty: "Nenhum filtro selecionado", discipline: "Disciplina", subject: "Assunto", topic: "Tópico", difficulty: "Dificuldade", year: "Ano", board: "Banca", institution: "Instituição", career: "Carreira", education: "Escolaridade", alternatives: "Alternativas", resultEmpty: "Nenhuma questão encontrada." },
  "pt-PT": { title: "Filtrar questões", active: "ativos", show: "Mostrar filtros", hide: "Ocultar filtros", search: "Pesquisar", searchPlaceholder: "Código, disciplina ou enunciado", all: "Todas", clear: "Limpar filtros", selected: "filtro(s) selecionado(s)", empty: "Nenhum filtro selecionado", discipline: "Disciplina", subject: "Tema", topic: "Tópico", difficulty: "Dificuldade", year: "Ano", board: "Banca", institution: "Instituição", career: "Carreira", education: "Escolaridade", alternatives: "Alternativas", resultEmpty: "Nenhuma questão encontrada." },
  es: { title: "Filtrar preguntas", active: "activos", show: "Mostrar filtros", hide: "Ocultar filtros", search: "Buscar", searchPlaceholder: "Código, materia o enunciado", all: "Todas", clear: "Limpiar filtros", selected: "filtro(s) seleccionado(s)", empty: "Ningún filtro seleccionado", discipline: "Materia", subject: "Tema", topic: "Tópico", difficulty: "Dificultad", year: "Año", board: "Banca", institution: "Institución", career: "Carrera", education: "Nivel educativo", alternatives: "Alternativas", resultEmpty: "No se encontraron preguntas." },
  fr: { title: "Filtrer les questions", active: "actifs", show: "Afficher les filtres", hide: "Masquer les filtres", search: "Rechercher", searchPlaceholder: "Code, matière ou énoncé", all: "Toutes", clear: "Effacer les filtres", selected: "filtre(s) sélectionné(s)", empty: "Aucun filtre sélectionné", discipline: "Matière", subject: "Sujet", topic: "Thème", difficulty: "Difficulté", year: "Année", board: "Organisme", institution: "Institution", career: "Carrière", education: "Niveau d'études", alternatives: "Alternatives", resultEmpty: "Aucune question trouvée." },
}
